### ISSUE TITLE
registerCacheDriverTestSuite is missing

### ISSUE THREAD

**Issue by TiBianMod** [Julien-R44/bentocache-docs#2]
On section [Tests](https://bentocache.julr.dev/docs/custom-cache-driver#tests) the `registerCacheDriverTestSuite` function is missing from the exports of `bentocache`.

```ts
// bentocache don't provide any export with this name
import { registerCacheDriverTestSuite } from 'bentocache/tests'
```

**Comment by Julien-R44** [comment]
Nice catch, thanks. Gonna fix that today

Otherwise, did you intend to create a new custom driver? Maybe we can add this directly to bentocache?

**Comment by TiBianMod** [comment]
for the moment I don't have any plans to create a custom driver 😄 

yes, will be nice if you can added directly to bentocache.

**Comment by Julien-R44** [comment]
Cool. If you are missing any driver, feel free to raise another issue and yeah we can probably add it directly to bentocache 🤝

**Comment by Julien-R44** [comment]
Fixed with https://github.com/Julien-R44/bentocache/commit/86120af8edf52d445e570bd276e3eb19268b053f
Will release it tonight. Thanks!
