### ISSUE TITLE
Consistency of naming variables related to bentocache

### ISSUE THREAD

**Issue by TiBianMod** [Julien-R44/bentocache-docs#3]
during the  [PR #1](https://github.com/Julien-R44/bentocache-docs/pull/1)
I noticed, inconsistency on naming variables related to `bentocache` (of course this is up to you) 😄 

the names that are used for this vars are:
- bento
- cache
- bentocache
- bentoCache

I will like to make a second PR about the naming of this variables..

what will be your choice ?

- bento
- cache
- bentocache

I like `bento` or `cache` !!

note: I wanted to talk to you about this on Twitter, but I can't send you a message 🥲

**Comment by Julien-R44** [comment]
oops sorry. I've opened my DM messages on twitter, if needed next time 😅

I think we can go with `bento` if you like it too !
Thanks again for fixing these inconsistencies

**Comment by TiBianMod** [comment]
Thanks,

I like `bento` 👍
